### ISSUE TITLE
where do the inputs go?

### ISSUE THREAD

**Issue by whatSocks** [SoheilKhodayari/JAW#2]
Following along with the readme instructions, I'm putting my js program in the `hpg_contstuction/outputs` folder (I made a new directory called `test_inputs`):

<img width="237" alt="Screen Shot 2021-07-08 at 7 06 34 PM" src="https://user-images.githubusercontent.com/2731744/125000983-9e565c80-e01f-11eb-8def-de57b97bcb3a.png">

from root, i'm running various versions of:
```
python3 -m hpg_construction.api test_inputs/ --js=test_program
```

but I can't seem to get it to run without error

```
2021-07-08 19:05:20,711 - JAW - ERROR - Path of the program under analysis must be within the outputs folder. (api.py:62)
```

I tried:
```
	base_path = args['path']
	if constantsModule.OUTPUT_NODES_RELS_PATH not in base_path:
		logger.error(OUTPUT_NODES_RELS_PATH)
		sys.exit(1)
```
to see what it was looking for and got:

```
NameError: name 'OUTPUT_NODES_RELS_PATH' is not defined
```  

I got the same issue doing the test script:

```
python3 -m hpg_construction.api ./hpg_construction/outputs/test_website/test_webpage --hybrid=false
```

**Comment by SoheilKhodayari** [comment]
1. In the current state of the code, the `path` parameter should be passed in its absolute form. In your example, the following would work (when running from project root directory):
```
python3 -m hpg_construction.api $(pwd)/hpg_construction/outputs/test_inputs --js=test_program.js
```

- Having said that, I confirm that the issue exists when using `./` instead of `$(pwd)` as well as relative paths. I will push a patch for this soon. 

2. Please note that the error you are getting (`NameError: name 'OUTPUT_NODES_RELS_PATH' is not defined`) is because of a typo in your code, where you should log `constantsModule.OUTPUT_NODES_RELS_PATH` instead of the undefined variable `OUTPUT_NODES_RELS_PATH`.

- Also, note that `constantsModule.OUTPUT_NODES_RELS_PATH` is defined in `constants.py` and refers to `$(pwd)/hpg_construction/outputs`, which is the base path where output nodes and relationship files for the property graph are created in.

**Comment by whatSocks** [comment]
OK I managed to get the CSVs to appear, but they appear in a directory called `undefined` which seems erroneous since the program seem to be expecting the CSVs to be in `outputs`. 

<img width="210" alt="Screen Shot 2021-07-17 at 11 22 50 PM" src="https://user-images.githubusercontent.com/2731744/126054573-79573670-f6fa-43be-afe8-8263139b0f5f.png"> 

My test file is `resolve-plays-favorites.js`

I moved a copy of the csvs to `outputs` but get errors on the create steps:
```
sed: 1: "/etc/neo4j/neo4j.conf": extra characters at the end of n command
```

Further the output.db seems to be created not in the place I expected (the one I created on Neo4j desktop) but elsewhere on my computer.

**Comment by SoheilKhodayari** [comment]
(i) Please move your input file `resolve-plays-favorites.js` to a folder of your choice inside `outputs`. For example: `outputs/test_folder/resolve-plays-favorites.js`. In this case, the `nodes.csv` and `rels.csv` files will be created inside the `test_folder`. The tool currently expects each input script to be in its own folder. 

(ii) Are you using a `macOS` or `linux`? 
- by default, the output db file will be stored in the neo4j default databases folder, which is `var/lib/neo4j/data/databases` for linux, and `/usr/local/Cellar/neo4j/<version>/libexec/data/databases` for macOS. Please see [here](https://github.com/SoheilKhodayari/JAW/blob/master/constants.py#L57) and adjust the setting according your neo4j installation.  
- The `sed` command is used to change the `active` neo4j database in neo4j.conf after the import is completed (see [here](https://github.com/SoheilKhodayari/JAW/blob/master/hpg_neo4j/db_utility.py#L171)). The syntax of this command is different for macOS and linux. If you are using `macOS`,  please create a `.env` file with `PLATFORM=macos` (see the end of this [doc](https://github.com/SoheilKhodayari/JAW/blob/master/docs/installation.md))

(iii) Finally, I strongly suggest you to see and run the example [here](https://github.com/SoheilKhodayari/JAW/blob/master/hpg_analysis/example/example_analysis.py) showing how the tool can be used for an example JavaScript file and with neo4j in `docker`, as then you don't have to worry about the configuration in (ii).

**Comment by whatSocks** [comment]
First, thank you for your help. 

As suggested in [the example](https://github.com/SoheilKhodayari/JAW/blob/master/hpg_analysis/example/example_analysis.py) I ran the following from the root of the project. 

`python3 -m hpg_analysis.example.example_analysis` 

In my constants.py I verified the user and pass were the defaults:
```
# neo4j credential
NEO4J_USER = "neo4j"
NEO4J_PASS = 'root'
```

In I see the import was successful:

```
2021-07-18 11:00:58,072 - JAW - DEBUG - Running command: docker run     --name neo4j_container     -p7474:7474 -p7687:7687     -d     -v /JAW/docker/neo4j/volume/neo4j/data:/data     -v /JAW/docker/neo4j/volume/neo4j/logs:/logs     -v /JAW/hpg_construction/outputs:/var/lib/neo4j/import     -v /JAW/docker/neo4j/volume/neo4j/plugins:/plugins     -e NEO4J_apoc_export_file_enabled=true     -e NEO4J_apoc_import_file_enabled=true     -e NEO4J_apoc_import_file_use__neo4j__config=true     -e NEO4JLABS_PLUGINS='["apoc"]'     -e NEO4J_dbms_security_procedures_unrestricted=apoc.\\*     -e PYTHONUNBUFFERED=1     --env NEO4J_AUTH=neo4j/root     neo4j:4.2.3
```
...
```
IMPORT DONE in 1s 281ms.
Imported:
26 nodes
34 relationships
180 properties
```

but then I get some errors. 

```
neo4j.exceptions.AuthError: {code: None} {message: None}
```

Wanting to validate that at least the data got in, I open the docker neo4j db but see I can't authenticate with neo4j/root

<img width="839" alt="Screen Shot 2021-07-18 at 11 06 32 AM" src="https://user-images.githubusercontent.com/2731744/126072255-381f4102-980e-416c-9814-057c1a715efb.png">

**Comment by SoheilKhodayari** [comment]
Thank you for reporting the Neo4j authentication problem. Unfortunately, I am unable to reproduce this error.

However, I found a reference to this issue in [neo4j docker](https://github.com/neo4j/docker-neo4j/issues/163#issuecomment-491282701),  and pushed a commit following the suggestion on that thread.

Could you please check if the above commit would fix your problem or not?
If not, may I ask if you are using the latest version of the docker engine? thanks!

**Comment by whatSocks** [comment]
I'm on docker engine 20.10.7 and updated right before my attempt today.

**Comment by whatSocks** [comment]
tried it again and got a different result:

```
IMPORT DONE in 1s 460ms.
Imported:
26 nodes
34 relationships
180 properties
Peak memory usage: 479.2MiB (utility.py:97)
2021-07-18 15:29:54,468 - JAW - INFO - waiting for the tcp port 7474 of the neo4j container to be ready... (example_analysis.py:114)
2021-07-18 15:30:24,851 - JAW - INFO - neo4j is now ready to accept bolt connections. (db_utility.py:287)
<Node id=3 labels=frozenset({'ASTNode'}) properties={'Type': 'Program', 'Id': '1', 'Range': '[925,1013]', 'Location': '{start:{line:29,column:0},end:{line:34,column:1}}'}>
2021-07-18 15:30:26,023 - JAW - DEBUG - Running command: docker stop neo4j_container (utility.py:82)
2021-07-18 15:30:33,573 - JAW - WARNING - Docker container neo4j_container is being stopped. (manage_container.py:100)
``` 
It stops itself so I don't have much chance to see what's happening

**Comment by SoheilKhodayari** [comment]
Okay, many thanks for the info. The problem is solve now! The example script runs a simple `cypher` query, and you can see
the output in the log you provided:
```
<Node id=3 labels=frozenset({'ASTNode'}) properties={'Type': 'Program', 'Id': '1', 'Range': '[925,1013]', 'Location': '{start:{line:29,column:0},end:{line:34,column:1}}'}>
```

**Comment by whatSocks** [comment]
great thank you :)
