### ISSUE TITLE
neo4j version not available [Ubuntu 21.10]

### ISSUE THREAD

**Issue by ma08** [SoheilKhodayari/JAW#6]
https://github.com/SoheilKhodayari/JAW/blob/7c0e71d8c121f1ab6c8a4584ca5c5a10bf9ba738/installation/linux_neo4j_installation.sh#L5

```
...
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Version '3.5.9' for 'neo4j' was not found
```

Maybe keep the version more generic?

**Comment by ma08** [comment]
When I run `sudo apt-get install neo4j` the version installed is `3.5.14` (Ubuntu 21.10).

**Comment by SoheilKhodayari** [comment]
Thanks for reporting this. It seems that [debian.neo4j.org](https://debian.neo4j.org/repo) is also deprecated. I'll fix the script
