### ISSUE TITLE
Misplaced `x` char

### ISSUE THREAD

**Issue by mal-tee** [SoheilKhodayari/JAW#8]
While trying to run `TheThing` I encountered this `x` at the beginning of the file, leading to a crash:

https://github.com/SoheilKhodayari/JAW/blob/b0d5044e026f133e50a9d42d3db6ffc39c4d9e04/analyses/domclobbering/domc_traversals.js#L1

I assume it's a typo?

**Comment by SoheilKhodayari** [comment]
Indeed it is, thanks for reporting.
